# -*- coding: utf-8 -*-
"""苍穹外卖项目面试全解 - 正文 PDF 生成（ReportLab, 封面另行合并）"""
import os, sys, hashlib, re

PDF_SKILL_DIR = r"C:\Users\28402\.zcode\cli\plugins\cache\zcode-plugins-official\document-skills\0.1.4\skills\pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, HRFlowable, KeepTogether,
                                CondPageBreak)
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Polygon, Circle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ 字体（local-font-first：Windows 本机字体） ━━
pdfmetrics.registerFont(TTFont('MSYH', 'C:/Windows/Fonts/msyh.ttc', subfontIndex=0))
pdfmetrics.registerFont(TTFont('MSYH-B', 'C:/Windows/Fonts/msyhbd.ttc', subfontIndex=0))
pdfmetrics.registerFont(TTFont('SIMHEI', 'C:/Windows/Fonts/simhei.ttf'))
pdfmetrics.registerFont(TTFont('CONSOLA', 'C:/Windows/Fonts/consola.ttf'))
registerFontFamily('MSYH', normal='MSYH', bold='MSYH-B')
registerFontFamily('SIMHEI', normal='SIMHEI', bold='SIMHEI')
registerFontFamily('CONSOLA', normal='CONSOLA', bold='CONSOLA')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Color Palette (auto-generated by pdf.py palette.cascade) ━━
PAGE_BG      = colors.HexColor('#f3f3f2')
CARD_BG      = colors.HexColor('#eeeeeb')
TABLE_STRIPE = colors.HexColor('#f1f0ef')
HEADER_FILL  = colors.HexColor('#5c543a')
COVER_BLOCK  = colors.HexColor('#8a7c53')
BORDER       = colors.HexColor('#c7bea5')
ICON         = colors.HexColor('#7e6d3b')
ACCENT       = colors.HexColor('#2587a8')
ACCENT_SOFT  = colors.HexColor('#e3f0f5')   # accent 淡化（图元底色）
TEXT_PRIMARY = colors.HexColor('#201f1d')
TEXT_MUTED   = colors.HexColor('#85837b')
TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD  = TABLE_STRIPE

# ━━ 页面几何 ━━
MARGIN = 2.1 * cm
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN          # ≈ 471pt
AVAIL_H = PAGE_H - 2 * MARGIN

# ━━ 样式 ━━
def st(name, **kw):
    base = dict(fontName='MSYH', fontSize=10.5, leading=17, alignment=TA_LEFT,
                wordWrap='CJK', textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=8)
    base.update(kw)
    return ParagraphStyle(name, **base)

body      = st('Body', firstLineIndent=21)
body_ni   = st('BodyNI')
bullet    = st('Bullet', leftIndent=14, spaceAfter=4)
h1        = st('H1', fontName='MSYH-B', fontSize=17, leading=24, spaceBefore=18, spaceAfter=4, textColor=TEXT_PRIMARY)
h2        = st('H2', fontName='MSYH-B', fontSize=13.5, leading=20, spaceBefore=14, spaceAfter=6, textColor=ACCENT)
h3        = st('H3', fontName='MSYH-B', fontSize=11, leading=17, spaceBefore=10, spaceAfter=4)
caption   = st('Caption', fontSize=8.5, leading=12, alignment=TA_CENTER, textColor=TEXT_MUTED, spaceAfter=6, spaceBefore=2)
code_st   = st('Code', fontName='CONSOLA', fontSize=8.6, leading=12.5, spaceAfter=0, textColor=TEXT_PRIMARY)
callout_t = st('CalloutT', fontName='MSYH-B', fontSize=10.5, leading=16, textColor=ACCENT, spaceAfter=2)
callout_b = st('CalloutB', fontSize=9.8, leading=15.5, spaceAfter=0)
quote_st  = st('Quote', fontSize=9.8, leading=16, textColor=TEXT_MUTED, leftIndent=20)
th_st     = st('TH', fontName='MSYH-B', fontSize=9.5, leading=13, alignment=TA_CENTER, textColor=colors.white, spaceAfter=0)
td_st     = st('TD', fontSize=9.3, leading=13.5, spaceAfter=0)
td_c      = st('TDC', fontSize=9.3, leading=13.5, alignment=TA_CENTER, spaceAfter=0)
qa_q      = st('QAQ', fontName='MSYH-B', fontSize=10.2, leading=15, spaceBefore=8, spaceAfter=2, textColor=ACCENT)
qa_a      = st('QAA', fontSize=9.8, leading=15, leftIndent=12, spaceAfter=4)

# ━━ 通用构件 ━━
H1_ORPHAN = AVAIL_H * 0.18

def add_heading(text, style, level=0):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text; p.bookmark_level = level
    p.bookmark_text = text; p.bookmark_key = key
    return p

_chapter_open = [False]

def H1(story, text):
    _chapter_open[0] = True
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(KeepTogether([
        add_heading(text, h1, 0),
        HRFlowable(width='100%', thickness=1.4, color=ACCENT, spaceBefore=2, spaceAfter=10),
    ]))

def H2(story, text):
    if _chapter_open[0]:
        _chapter_open[0] = False      # 章标题后首个小节标题：与章标题同页，不二次跳页
    else:
        story.append(CondPageBreak(H1_ORPHAN * 1.5))
    story.append(add_heading(text, h2, 1))

def P(story, text, style=None):
    story.append(Paragraph(text, style or body))

def BL(story, items):
    for it in items:
        story.append(Paragraph('• ' + it, bullet))
    story.append(Spacer(1, 4))

def code_block(story, code_text, label=None):
    paras = []
    if label:
        paras.append(Paragraph(label, st('CodeLabel', fontName='MSYH-B', fontSize=8.6,
                     leading=13, textColor=TEXT_MUTED, spaceAfter=2)))
    AMP, LT, GT = chr(38), chr(60), chr(62)
    NBSP = AMP + 'nbsp;'
    CJK_CHARS = u'一-鿿　-〿＀-￯「」·'
    CJK_RE = re.compile('[' + CJK_CHARS + ']+')
    def _cjk(m):
        return '<font name="MSYH">' + m.group(0) + '</font>'
    for line in code_text.splitlines():
        esc = line.replace(AMP, AMP + 'amp;').replace(LT, AMP + 'lt;').replace(GT, AMP + 'gt;')
        esc = esc.replace(' ', NBSP)
        esc = CJK_RE.sub(_cjk, esc)
        paras.append(Paragraph(esc, code_st))
    t = Table([[paras]], colWidths=[AVAIL_W * 0.96])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), TABLE_STRIPE),
        ('LINEBEFORE', (0, 0), (0, -1), 2.2, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    t.hAlign = 'CENTER'
    story.append(Spacer(1, 4)); story.append(t); story.append(Spacer(1, 8))

def callout(story, title, text):
    inner = [Paragraph(title, callout_t), Paragraph(text, callout_b)]
    t = Table([[inner]], colWidths=[AVAIL_W * 0.96])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), ACCENT_SOFT),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    t.hAlign = 'CENTER'
    story.append(Spacer(1, 4)); story.append(t); story.append(Spacer(1, 8))

def make_table(story, header, rows, ratios, cap=None):
    data = [[Paragraph('<b>%s</b>' % c, th_st) for c in header]]
    for r in rows:
        data.append([Paragraph(c, td_st) if i == 0 else Paragraph(c, td_st) for i, c in enumerate(r)])
    widths = [x * AVAIL_W * 0.98 for x in ratios]
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 8)); story.append(t)
    if cap:
        story.append(Spacer(1, 4)); story.append(Paragraph(cap, caption))
    story.append(Spacer(1, 8))

# ━━ 矢量绘图助手（图元风格统一：淡底 + 强调色边框） ━━
def new_drawing(height):
    d = Drawing(AVAIL_W, height)
    d._bg()
    return d

def _bg(d):
    pass

def box(d, x, y, w, h, title, lines=None, fill=ACCENT_SOFT, border=ACCENT,
        ts=9.5, ds=7.8, tcolor=None, bw=1.0):
    d.add(Rect(x, y, w, h, rx=4, ry=4, fillColor=fill, strokeColor=border, strokeWidth=bw))
    cx = x + w / 2.0
    lines = lines or []
    if lines:
        d.add(String(cx, y + h - ts - 4, title, fontName='MSYH-B', fontSize=ts,
                     fillColor=tcolor or TEXT_PRIMARY, textAnchor='middle'))
        ly = y + h - ts - 4 - ds - 3.2
        for ln in lines:
            d.add(String(cx, ly, ln, fontName='MSYH', fontSize=ds, fillColor=TEXT_MUTED, textAnchor='middle'))
            ly -= ds + 2.4
    else:
        d.add(String(cx, y + (h - ts) / 2.0 + 0.5, title, fontName='MSYH-B', fontSize=ts,
                     fillColor=tcolor or TEXT_PRIMARY, textAnchor='middle'))

def arrow(d, x1, y1, x2, y2, color=TEXT_PRIMARY, w=0.9, dashed=False, label=None,
          ls=7.3, lcolor=None, lox=0, loy=3):
    import math
    ang = math.atan2(y2 - y1, x2 - x1)
    ah = 5.0
    bx, by = x2 - ah * math.cos(ang), y2 - ah * math.sin(ang)
    d.add(Line(x1, y1, bx, by, strokeColor=color, strokeWidth=w,
               strokeDashArray=[2.5, 2.5] if dashed else None))
    d.add(Polygon(points=[x2, y2, bx + ah*0.42*math.cos(ang+1.57), by + ah*0.42*math.sin(ang+1.57),
                          bx + ah*0.42*math.cos(ang-1.57), by + ah*0.42*math.sin(ang-1.57)],
                  fillColor=color, strokeColor=None))
    if label:
        mx, my = (x1 + x2) / 2.0 + lox, (y1 + y2) / 2.0 + loy
        d.add(String(mx, my, label, fontName='MSYH', fontSize=ls,
                     fillColor=lcolor or TEXT_MUTED, textAnchor='middle'))

def vlabel(d, x, y, text, size=7.3, color=None, anchor='middle', bold=False):
    d.add(String(x, y, text, fontName='MSYH-B' if bold else 'MSYH', fontSize=size,
                 fillColor=color or TEXT_MUTED, textAnchor=anchor))

def fig(story, drawing, cap, max_h=0.34 * PAGE_H):
    if drawing.height <= max_h:
        story.append(KeepTogether([Spacer(1, 6), drawing, Spacer(1, 2), Paragraph(cap, caption)]))
    else:
        story.append(Spacer(1, 6)); story.append(drawing)
        story.append(Spacer(1, 2)); story.append(Paragraph(cap, caption))
    story.append(Spacer(1, 6))

# ━━ 图 1：系统架构图 ━━
def fig_architecture():
    H = 258
    d = Drawing(AVAIL_W, H)
    m = 14
    def band(y, h, title, fill, items, item_fill, ts=8.8):
        d.add(Rect(m, y, AVAIL_W - 2 * m - 74, h, rx=5, ry=5, fillColor=fill,
                   strokeColor=BORDER, strokeWidth=0.8))
        vlabel(d, m + 8, y + h / 2 - 3, title, size=9, color=HEADER_FILL, anchor='start', bold=True)
        n = len(items); gap = 8
        iw = (AVAIL_W - 2 * m - 74 - 46 - gap * (n - 1)) / n
        ix = m + 42
        for it, itsub in items:
            box(d, ix, y + 9, iw, h - 18, it, itsub, fill=item_fill, border=BORDER, ts=8.8, ds=7.2)
            ix += iw + gap
    y0 = 18
    band(y0 + 3 * 58, 52, '客户端', CARD_BG,
         [('管理端 Web', ['nginx :80 · html/sky']), ('用户端小程序', ['微信登录 · 下单支付'])], PAGE_BG)
    band(y0 + 2 * 58 + 4, 52, '接入层', ACCENT_SOFT,
         [('Controller', ['admin / user / notify']), ('拦截器·全局异常', ['JWT 校验 · 统一返回'])], colors.white)
    band(y0 + 1 * 58 + 2, 52, '业务层', colors.white,
         [('Service', ['业务编排 · 事务']), ('AOP · 缓存 · 任务', ['AutoFill · Cache · Task'])], CARD_BG)
    band(y0, 52, '数据层', colors.white,
         [('MySQL 8', ['11 张业务表']), ('Redis', ['菜品缓存 · 会话'])], CARD_BG)
    for yy in (y0 + 52, y0 + 110, y0 + 168):
        arrow(d, AVAIL_W / 2 - 40, yy + 2, AVAIL_W / 2 - 40, yy + 10, w=1.0)
        arrow(d, AVAIL_W / 2 + 40, yy + 10, AVAIL_W / 2 + 40, yy + 2, w=1.0)
    sx = AVAIL_W - m - 62
    box(d, sx, y0 + 92, 66, 84, '第三方', ['阿里云 OSS', '图片存储', '微信支付/登录', '百度地图 AK'],
        fill=colors.white, border=ICON, ts=9)
    arrow(d, sx + 33, y0 + 140, sx + 33, y0 + 168, w=0.9)
    arrow(d, sx + 33, y0 + 128, sx + 33, y0 + 92, w=0.9, dashed=True)
    vlabel(d, sx + 33, y0 + 190, 'HTTP / SDK', size=7)
    return d

# ━━ 图 2：登录时序图 ━━
def fig_login_seq():
    H = 236
    d = Drawing(AVAIL_W, H)
    actors = [('管理端', 40), ('JwtTokenAdmin', 175), ('Employee', 300), ('MySQL', 420),
              ('线程上下文', 480)]
    actors = [('管理端前端', 58), ('EmployeeController', 168), ('EmployeeService', 288),
              ('MySQL/EmployeeMapper', 408)]
    top, bot = H - 26, 20
    for name, x in actors:
        box(d, x - 44, top, 88, 20, name, fill=CARD_BG, border=BORDER, ts=7.8)
        d.add(Line(x, top, x, bot, strokeColor=BORDER, strokeWidth=0.7, strokeDashArray=[3, 3]))
    msgs = [
        (58, 288, '1. POST /admin/employee/login（账号+密码）', 0),
        (288, 408, '2. 按用户名查询员工 getByUsername ', 22),
        (408, 288, '3. 返回 Employee（含 status=1 启用校验）', 42),
        (288, 288, '4. MD5 比对密码（不一致抛异常）', 64),
        (288, 168, '5. JwtUtil.createJwt( empId ) 生成令牌', 90),
        (168, 58, '6. Result.success(EmployeeLoginVO{ token })', 112),
        (58, 168, '7. 后续请求携带 header: token=xxx', 140),
        (168, 288, '8. 拦截器解析 JWT 校验通过', 162),
        (168, 408, '9. empId 写入 ThreadLocal（BaseContext）', 186),
    ]
    for x1, x2, label, dy in msgs:
        y = H - 50 - dy
        if x1 == x2:
            arrow(d, x1 + 26, y, x1 + 26, y - 12, w=0.9, label=None)
            vlabel(d, x1, y + 2, label, size=7.2, anchor='start')
        else:
            arrow(d, x1, y, x2, y, w=0.9,
                  dashed=(x1 in (408, 288) and dy in (42, 90, 112)))
            vlabel(d, (x1 + x2) / 2.0, y + 3, label, size=7.2)
    return d

# ━━ 图 3：AutoFill AOP 流程 ━━
def fig_autofill():
    H = 116
    d = Drawing(AVAIL_W, H)
    y = 30; bw2 = 96; gap = (AVAIL_W - 28 - 4 * bw2) / 3.0
    xs = [14 + i * (bw2 + gap) for i in range(4)]
    box(d, xs[0], y, bw2, 56, 'Mapper 方法', ['insert / update', '标注 @AutoFill'], fill=CARD_BG, border=BORDER)
    box(d, xs[1], y, bw2, 56, 'AutoFillAspect', ['@Before 环绕点', 'execution 切入'], ts=9)
    box(d, xs[2], y, bw2, 56, '反射填充公共字段', ['create/updateTime', 'create/updateUser'], ts=8.6)
    box(d, xs[3], y, bw2, 56, 'SQL 执行落库', ['字段由切面补全', 'Service 零侵入'], fill=colors.white, border=BORDER)
    for i in range(3):
        arrow(d, xs[i] + bw2, y + 28, xs[i + 1], y + 28, w=1.0)
    vlabel(d, 14 + bw2 + gap / 2, y + 32, '', 7)
    return d

# ━━ 图 4：数据库 ER 关系图 ━━
def fig_er():
    H = 268
    d = Drawing(AVAIL_W, H)
    bw2, bh = 92, 40
    def tbl(x, y, name, fields, strong=False):
        b = ACCENT if strong else BORDER
        d.add(Rect(x, y, bw2, bh, rx=3, ry=3, fillColor=colors.white, strokeColor=b, strokeWidth=1.0 if strong else 0.8))
        d.add(Rect(x, y + bh - 13, bw2, 13, rx=3, ry=3, fillColor=ACCENT_SOFT, strokeColor=b, strokeWidth=0.8))
        d.add(String(x + bw2 / 2, y + bh - 10.5, name, fontName='MSYH-B', fontSize=8,
                     fillColor=TEXT_PRIMARY, textAnchor='middle'))
        for i, f in enumerate(fields[:2]):
            d.add(String(x + 5, y + bh - 22 - i * 9.5, f, fontName='MSYH', fontSize=6.8,
                         fillColor=TEXT_MUTED, textAnchor='start'))
    c1, c2, c3, c4 = 14, 136, 258, 380
    tbl(c1, 190, 'employee', ['id · username', 'password(MD5)'])
    tbl(c1, 120, 'user', ['id · openid', '微信登录账户'])
    tbl(c1, 44, 'address_book', ['user_id 外键', 'is_default'], strong=True)
    tbl(c2, 190, 'category', ['id · type', '1菜品/2套餐'])
    tbl(c2, 96, 'shopping_cart', ['user_id · dish_id', 'setmeal_id · number'])
    tbl(c2, 22, 'orders', ['number · status', 'amount · address_id'], strong=True)
    tbl(c3, 190, 'dish', ['category_id', 'price · status'], strong=True)
    tbl(c3, 120, 'setmeal', ['category_id', 'price · image'])
    tbl(c3, 44, 'order_detail', ['order_id', 'dish/setmeal_id'], strong=True)
    tbl(c4, 190, 'dish_flavor', ['dish_id', 'name · value'])
    tbl(c4, 96, 'setmeal_dish', ['setmeal_id', 'dish_id · copies'])
    def rel(x1, y1, x2, y2, label, dashed=False):
        arrow(d, x1, y1, x2, y2, w=0.8, color=TEXT_MUTED, dashed=dashed)
        lx = x1 + (x2 - x1) * 0.42
        ly = y1 + (y2 - y1) * 0.42 + 3
        vlabel(d, lx, ly, label, size=6.8)
    rel(c1 + bw2, 210, c2, 210, '1:N')
    rel(c1 + bw2, 138, c2 + 10, 120, '1:N')
    rel(c1 + bw2, 64, c2, 40, '1:N')
    rel(c2 + bw2, 210, c3, 212, '1:N 菜品')
    rel(c2 + bw2, 205, c3, 140, '1:N 套餐')
    rel(c2 + bw2, 116, c3, 88, '1:N')
    rel(c2 + bw2, 40, c3, 46, '1:N')
    rel(c3 + bw2, 210, c4, 210, '1:N')
    rel(c3 + bw2, 140, c4, 116, '1:N')
    vlabel(d, 14, 6, '说明：订单/购物车等仅存关联 id（逻辑外键），不建物理外键约束，由应用层保证一致性。',
           size=7.2, anchor='start')
    return d

# ━━ 图 5：缓存读写流程 ━━
def fig_cache():
    H = 190
    d = Drawing(AVAIL_W, H)
    y = 128
    box(d, 14, y, 86, 44, '查询请求', ['GET /user/dish'], fill=CARD_BG, border=BORDER)
    box(d, 148, y, 100, 44, '查 Redis 缓存', ['@Cacheable', 'key=categoryId'], ts=9)
    # 判断菱形
    dx, dy, dw, dh = 300, y - 6, 92, 56
    d.add(Polygon(points=[dx + dw/2, dy + dh, dx + dw, dy + dh/2, dx + dw/2, dy, dx, dy + dh/2],
                  fillColor=ACCENT_SOFT, strokeColor=ACCENT, strokeWidth=1))
    d.add(String(dx + dw/2, dy + dh/2 - 3, '命中?', fontName='MSYH-B', fontSize=9,
                 fillColor=TEXT_PRIMARY, textAnchor='middle'))
    box(d, 410, y + 4, 62, 36, '命中', ['直接返回'], fill=colors.white, border=BORDER, ts=8.8)
    box(d, 300, 62, 92, 40, '查 MySQL', ['Mapper 查询'], fill=colors.white, border=BORDER)
    box(d, 148, 58, 100, 40, '结果写入 Redis', ['下次直接命中'], ts=8.8)
    box(d, 14, 58, 86, 40, '返回数据', [], fill=CARD_BG, border=BORDER)
    arrow(d, 100, y + 22, 148, y + 22, w=1)
    arrow(d, 248, y + 22, dx, y + 22, w=1)
    arrow(d, dx + dw, y + 22, 410, y + 22, w=1, label='是', loy=3)
    arrow(d, dx + dw/2, dy, 346, 102, w=1, label='否', lox=8, loy=-2)
    arrow(d, 300, 82, 248, 78, w=1)
    arrow(d, 148, 78, 100, 78, w=1)
    box(d, 252, 8, 208, 34, '写操作（新增/修改/删除/起售停售）',
        ['@CacheEvict 直接删除对应 cacheKey，保证一致性'], fill=ACCENT_SOFT, border=ACCENT, ts=8.6, ds=7.2)
    vlabel(d, 505, 8, '', 7)
    return d

# ━━ 图 6：订单状态机 ━━
def fig_order_state():
    H = 172
    d = Drawing(AVAIL_W, H)
    y = 96
    w2 = 84
    xs = [12 + i * (w2 + 36) for i in range(4)]
    box(d, xs[0], y, w2, 42, '1 待付款', ['下单未支付'], fill=CARD_BG, border=BORDER)
    box(d, xs[1], y, w2, 42, '2 待接单', ['已支付'], ts=9)
    box(d, xs[2], y, w2, 42, '3 已接单', ['派送中'], ts=9)
    box(d, xs[3], y, w2, 42, '4 已完成', ['交易结束'], fill=ACCENT_SOFT, border=ACCENT)
    for i in range(3):
        lbl = ['支付成功', '商家接单', '送达'][i]
        arrow(d, xs[i] + w2, y + 21, xs[i + 1], y + 21, w=1.1)
        vlabel(d, xs[i] + w2 + 29, y + 25, lbl, size=7.2)
    box(d, xs[0] + 8, 26, 106, 36, '5 已取消', ['超时/用户取消'], fill=colors.white, border=ICON, ts=9, ds=7.2)
    box(d, xs[1] + 42, 26, 106, 36, '6 已退款', ['商家拒单'], fill=colors.white, border=ICON, ts=9, ds=7.2)
    arrow(d, xs[0] + w2 / 2, y, xs[0] + 61, 62, w=0.9, dashed=True)
    vlabel(d, xs[0] + 122, 86, '支付超时15min(定时任务)/用户取消', size=6.9)
    arrow(d, xs[1] + w2 / 2, y, xs[1] + 95, 62, w=0.9, dashed=True)
    vlabel(d, xs[1] + 138, 86, '商家拒单 → 原路退款', size=6.9)
    return d

# ━━ 图 7：WebSocket 来单提醒 ━━
def fig_ws():
    H = 176
    d = Drawing(AVAIL_W, H)
    actors = [('用户端', 58), ('后端 paySuccess', 182), ('WebSocketServer', 318), ('管理端(浏览器)', 428)]
    top, bot = H - 24, 16
    for name, x in actors:
        box(d, x - 46, top, 92, 20, name, fill=CARD_BG, border=BORDER, ts=7.8)
        d.add(Line(x, top, x, bot, strokeColor=BORDER, strokeWidth=0.7, strokeDashArray=[3, 3]))
    msgs = [
        (58, 182, '1. 支付成功回调 /notify/paySuccess', 6, False),
        (182, 182, '2. 修改订单状态 → 待接单', 30, True),
        (182, 318, '3. sendToAllClient(type,orderId)', 54, False),
        (318, 428, '4. 推送消息（来单弹窗+语音）', 78, False),
        (58, 318, '5. 用户催单 reminder → 同通道推送', 108, False),
    ]
    for x1, x2, label, dy, self_msg in msgs:
        y = H - 46 - dy
        if self_msg:
            vlabel(d, x1, y + 2, label, size=7.2, anchor='start')
            arrow(d, x1 + 24, y, x1 + 24, y - 11, w=0.9)
        else:
            arrow(d, x1, y, x2 - 3 if x2 > x1 else x2 + 3, y, w=0.9)
            vlabel(d, (x1 + x2) / 2, y + 3, label, size=7.2)
    vlabel(d, AVAIL_W / 2, 6, '对比轮询：轮询需客户端定时请求、有延迟且浪费请求；WebSocket 服务端可主动推送、实时性高。',
           size=7.2)
    return d

# ━━ 图 8：AI Agent 工具调用循环 ━━
def fig_agent():
    H = 240
    d = Drawing(AVAIL_W, H)
    box(d, 14, 178, 100, 40, '用户提问', ['今天生意怎么样？'], fill=CARD_BG, border=BORDER, ds=7.2)
    box(d, 168, 172, 118, 52, 'AiAgentService', ['组装 messages+tools', '读取 Redis 会话历史'], ds=7.2)
    box(d, 344, 172, 118, 52, '大模型（GLM 等）', ['OpenAI 兼容接口', 'function calling'], fill=ACCENT_SOFT, border=ACCENT, ds=7.2)
    arrow(d, 114, 198, 168, 198, w=1, label='1 提问', loy=3)
    arrow(d, 286, 198, 344, 198, w=1, label='2 请求', loy=3)
    box(d, 344, 84, 118, 50, 'tool_calls?', ['模型自主决定', '调用哪些工具'], fill=colors.white, border=BORDER, ds=7.2)
    arrow(d, 403, 172, 403, 134, w=1, dashed=True)
    box(d, 168, 84, 118, 50, '执行业务工具', ['营业数据/销量榜', '菜品检索/订单统计'], ts=9, ds=7.2)
    arrow(d, 344, 109, 286, 109, w=1, label='3 解析', loy=3)
    box(d, 14, 84, 100, 50, 'Mapper/Service', ['复用现有业务层', '返回真实数据'], fill=CARD_BG, border=BORDER, ds=7.2)
    arrow(d, 168, 109, 114, 109, w=1)
    box(d, 168, 14, 294, 44, '工具结果以 role=tool 回填 → 再次请求模型 → 循环，直到模型给出最终回答',
        ['reply + toolTrace 一并返回；会话存 Redis（sessionId 隔离，2 小时过期）'],
        fill=ACCENT_SOFT, border=ACCENT, ts=8.6, ds=7.2)
    arrow(d, 227, 84, 227, 58, w=1)
    vlabel(d, 403, 164, '无需工具时直接回答', size=6.8)
    return d

# ━━ 页眉页脚 ━━
DOC_TITLE = '苍穹外卖项目面试全解'
def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('MSYH', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 1.2 * cm, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 1.32 * cm, PAGE_W - MARGIN, PAGE_H - 1.32 * cm)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 1.05 * cm, 'Sky Take-out · Interview Guide')
    canvas.drawRightString(PAGE_W - MARGIN, 1.05 * cm, '第 %d 页' % (doc.page + 1))
    canvas.restoreState()

# ━━ 组装文档 ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page + 1, key))

doc = TocDocTemplate(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), 'body.pdf'),
    pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN + 0.4 * cm, bottomMargin=MARGIN + 0.2 * cm,
    title='苍穹外卖项目面试全解', author='Z.ai', creator='Z.ai',
    subject='苍穹外卖 Spring Boot 项目从零讲解与面试准备')

story = []

# ── 目录 ──
from reportlab.platypus.tableofcontents import TableOfContents
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC1', fontName='MSYH-B', fontSize=10.5, leading=16.5, leftIndent=6, textColor=TEXT_PRIMARY),
    ParagraphStyle('TOC2', fontName='MSYH', fontSize=9.5, leading=14.5, leftIndent=26, textColor=TEXT_MUTED),
]
story.append(Paragraph('目录', st('TocTitle', fontName='MSYH-B', fontSize=18, leading=26, spaceAfter=12)))
story.append(toc)
story.append(PageBreak())

# ═══ 第一章 项目全景 ═══
H1(story, '第一章 项目全景：这是个什么项目')

H2(story, '1.1 一句话讲清楚')
P(story, '苍穹外卖（Sky Take-out）是一套<b>餐饮企业级外卖点餐系统</b>，分为两端：<b>管理端</b>（PC 网页，供商家管理菜品、'
 '套餐、订单、员工与查看营业报表）与<b>用户端</b>（微信小程序，供顾客浏览菜品、加购物车、下单支付）。',
 body_ni)
P(story, '后端是一个标准的 Spring Boot 单体多模块工程：对外提供 REST 接口，用 MySQL 持久化业务数据，'
 'Redis 做菜品缓存与会话存储，WebSocket 做来单提醒，Spring Task 做订单超时处理，并集成阿里云 OSS、微信支付/登录、'
 '百度地图等第三方能力。在此之上，我新增了一个<b>基于大模型工具调用（Function Calling）的智能运营 Agent</b>，'
 '这是本项目区别于普通教学项目的亮点，详见第五章。', body_ni)

H2(story, '1.2 技术栈总览')
make_table(story, ['类别', '技术', '在项目中的用途'], [
    ['框架', 'Spring Boot 2.7.3 / Spring MVC', '整体骨架与 REST 接口'],
    ['持久层', 'MyBatis + PageHelper', 'SQL 映射（注解+XML 混用）、物理分页'],
    ['数据库', 'MySQL 8.0', '11 张业务表，Druid 连接池'],
    ['缓存', 'Redis（Spring Cache / Spring Data Redis）', '菜品/套餐缓存、店铺状态、Agent 会话历史'],
    ['登录认证', 'JWT（jjwt）+ 拦截器 + ThreadLocal', '无状态登录、当前员工上下文'],
    ['AOP', 'AspectJ', '@AutoFill 公共字段自动填充'],
    ['实时通信', 'WebSocket（@ServerEndpoint）', '来单提醒、催单推送'],
    ['任务调度', 'Spring Task（@Scheduled）', '支付超时订单取消、派送中订单定时完成'],
    ['报表', 'Apache POI', '近 30 天营业数据 Excel 导出'],
    ['接口文档', 'Knife4j（Swagger）', 'doc.html 在线调试，@Api/@ApiOperation 分组'],
    ['第三方', '阿里云 OSS、微信支付/登录、百度地图', '图片存储、支付与登录、地址解析'],
], [0.16, 0.36, 0.48], cap='表 1-1 技术栈与用途')

H2(story, '1.3 系统架构图')
P(story, '整体是经典的前后端分离 + 分层架构。Nginx 承担静态资源托管与反向代理（/api/ 转发到后端 /admin/，'
 '/ws/ 支持 WebSocket 升级），后端按「接入层 - 业务层 - 数据层」组织代码。')
fig(story, fig_architecture(), '图 1-1 系统架构分层图')

H2(story, '1.4 工程结构：Maven 多模块')
make_table(story, ['模块', '职责', '代表性内容'], [
    ['sky-common', '公共基础件', 'Result 统一返回、JwtUtil、AiClientUtil、常量/异常/属性类、BaseContext'],
    ['sky-pojo', '数据模型', 'Entity（11 张表）、DTO（入参）、VO（出参）三套对象分离'],
    ['sky-server', '业务服务', 'Controller / Service / Mapper / Config / Task / WebSocket，最终打可执行 jar'],
], [0.18, 0.2, 0.62], cap='表 1-2 Maven 模块划分')
P(story, '<b>面试要点</b>：为什么 Entity/DTO/VO 要分三套？——解耦数据表结构与接口契约：表加字段不影响前端协议；'
 '入参做校验裁剪；出参按页面需要组装（如 DishVO 比实体多出 categoryName 与 flavors 集合）。', body_ni)

# ═══ 第二章 一次请求的完整旅程 ═══
H1(story, '第二章 一次请求的完整旅程')

H2(story, '2.1 登录：MD5 校验、JWT 签发与 ThreadLocal')
P(story, '管理端登录是理解本项目「请求处理链」的最佳入口，完整时序如下：')
fig(story, fig_login_seq(), '图 2-1 管理端登录与后续请求鉴权时序')
code_block(story, '''// JwtTokenAdminInterceptor（简化）
preHandle():
  String token = request.getHeader(jwtProperties.getAdminTokenName());
  Claims claims = JwtUtil.parseJWT(secretKey, token);      // 校验失败抛异常
  Long empId = Long.valueOf(claims.get(JwtClaimsConstant.EMP_ID).toString());
  BaseContext.setCurrentId(empId);                          // 存入 ThreadLocal
  return true;''', label='代码 2-1 拦截器核心逻辑')
callout(story, '面试高频：为什么用 ThreadLocal？',
 '一次请求对应一个 Tomcat 线程。拦截器解析出 empId 后存入 ThreadLocal，后续 Service/Mapper 层（如 AutoFill '
 '填充 create_user）直接 BaseContext.getCurrentId() 取用，避免层层传参；请求结束后线程归还线程池，'
 '若不 remove 会发生数据串号（线程复用脏读），所以拦截器 afterCompletion 中要调用 remove。')

H2(story, '2.2 统一返回与全局异常处理')
BL(story, [
 '<b>Result<T></b> 统一返回：code=1 成功 / 0 失败，前端约定好统一解析。',
 '<b>GlobalExceptionHandler</b>（@ControllerAdvice + @ExceptionHandler）：拦截三类异常——'
 'SQL 主键冲突（如员工账号重复，转成「账号 x 已存在」）、业务异常基类 BaseException（直接透出 message）、'
 '兜底 Exception（返回「系统繁忙」）。'])
P(story, '业务异常体系：AccountNotFoundException、PasswordErrorException 等全部继承 BaseException（RuntimeException），'
 'Service 层只管 throw，让异常沿调用栈冒泡到统一处理器，Controller 保持零 try-catch。', body_ni)

H2(story, '2.3 @AutoFill：AOP + 反射统一填充公共字段')
P(story, 'employee、dish、orders 等表都有 create_time / update_time / create_user / update_user 四个公共字段。'
 '逐个 Service 手工 set 重复且易漏，项目用「自定义注解 + AOP 切面 + 反射」统一解决：')
fig(story, fig_autofill(), '图 2-2 @AutoFill 自动填充：INSERT 填 4 个字段、UPDATE 填 2 个字段，当前操作人来自 ThreadLocal')
code_block(story, '''@AutoFill(value = OperationType.INSERT)          // 标在 Mapper 方法上
void insert(Dish dish);

@Aspect @Component
public class AutoFillAspect {
    @Before("execution(* com.sky.mapper.*.*(..)) && @annotation(autoFill)")
    public void autoFill(JoinPoint joinPoint, AutoFill autoFill) {
        Object entity = joinPoint.getArgs()[0];              // 第一个参数是实体
        LocalDateTime now = LocalDateTime.now();
        Long id = BaseContext.getCurrentId();                // 来自 ThreadLocal
        if (autoFill.value() == OperationType.INSERT) {
            invokeSetter(entity, "setCreateTime", now);
            invokeSetter(entity, "setCreateUser", id);
        }
        invokeSetter(entity, "setUpdateTime", now);
        invokeSetter(entity, "setUpdateUser", id);
    }
}''', label='代码 2-2 注解与切面（简化）')
callout(story, '面试高频：切面为什么切 Mapper 层而不是 Service 层？',
 '公共字段的承载者是实体，而实体是 Mapper insert/update 的直接入参；切 Mapper 层可以通过 @annotation 声明式地'
 '精确匹配方法，且所有业务路径天然收敛到这批方法上。另外填充动作发生在 SQL 参数组装之前，保证写库即生效。')

# ═══ 第三章 数据与缓存 ═══
H1(story, '第三章 数据设计与 Redis 缓存')

H2(story, '3.1 数据库设计：11 张表与逻辑外键')
fig(story, fig_er(), '图 3-1 核心表关系图（1:N，逻辑外键）')
P(story, '<b>设计取舍</b>：项目刻意<b>不建物理外键</b>，只存关联 id，由应用层保证一致性。好处是插入/删除不需要约束检查，'
 '分库分表友好，避免死锁；代价是要在业务代码里自己维护关联（如删除套餐前校验是否在售）。'
 '订单表 orders 与 order_detail 是典型的一单多明细，下单时<b>批量插入</b>明细。', body_ni)
callout(story, '面试追问：订单号为什么用时间戳？',
 'number = System.currentTimeMillis() + 随机串，生成简单、趋势递增利于索引；但它不是严格递增的全局唯一 ID，'
 '高并发下应使用雪花算法或数据库号段模式——这是可以主动向面试官提出的改进点。')

H2(story, '3.2 缓存：@Cacheable 读流程与缓存一致性')
fig(story, fig_cache(), '图 3-2 菜品缓存读写与失效流程')
code_block(story, '''// 用户端查询：按分类查菜品，缓存到 Redis
@Cacheable(cacheNames = "dishCache", key = "#dishDTO.categoryId")
public List<DishVO> listWithFlavor(Long categoryId) { ... return dishMapper.list(...); }

// 管理端写操作：直接删除缓存，下次查询重建
@CacheEvict(cacheNames = "dishCache", key = "#dishDTO.categoryId")
public void update(DishDTO dishDTO) { ... }''', label='代码 3-1 Spring Cache 注解用法')
BL(story, [
 '<b>为什么用删除缓存而不是更新缓存？</b>写多读少时更新缓存浪费；并发「先更新库再更新缓存」会出现旧值覆盖新值。删除策略把重建时机推迟到下一次读，天然一致。',
 '<b>为什么不用延迟双删/Canal？</b>本项目是单体 + 单 Redis，删缓存已够用；Canal 订阅 binlog 是多数据源场景的进阶方案——面试可主动展开。',
 '<b>店铺营业状态</b>没有走 Spring Cache：用 StringRedisTemplate 直接读写一个整数 key（SET/GET）。这是缓存开关量的最简形态。'])

# ═══ 第四章 业务主线 ═══
H1(story, '第四章 业务主线：订单、提醒、任务与报表')
P(story, '本章沿业务主线走一遍：先看订单状态如何流转，再看来单提醒如何实时送达管理端，'
 '然后是定时任务对超时订单的清理，最后过一遍微信支付与 POI 报表两个集成点。', body_ni)

_chapter_open[0] = False
story.append(CondPageBreak(280))
story.append(KeepTogether([
    add_heading('4.1 订单状态机', h2, 1),
    Spacer(1, 6), fig_order_state(), Spacer(1, 2),
    Paragraph('图 4-1 订单状态流转图', caption)]))
P(story, '下单流程：校验收货地址（异常抛 AddressBookBusinessException，前端引导去填地址）→ 校验购物车非空 →'
 '组装 orders + 批量插入 order_detail → 清空购物车 → 返回订单号与金额。支付成功后状态 1 → 2，并触发 WebSocket 推送。'
 '支付超时 15 分钟未付款的订单由定时任务自动取消（状态 5）。', body_ni)

H2(story, '4.2 WebSocket 来单提醒')
fig(story, fig_ws(), '图 4-2 来单提醒与催单推送时序')
code_block(story, '''@Component
@ServerEndpoint("/ws/{sid}")
public class WebSocketServer {
    private static Map<String, Session> sessionMap = new ConcurrentHashMap<>();
    @OnOpen  public void onOpen(Session session, @PathParam("sid") String sid) { sessionMap.put(sid, session); }
    @OnClose public void onClose(Session session, @PathParam("sid") String sid) { sessionMap.remove(sid); }
    public static void sendToAllClient(String message) {   // 广播给所有在线管理端
        sessionMap.values().forEach(s -> s.getBasicRemote().sendText(message));
    }
}''', label='代码 4-1 WebSocket 服务端（简化）')

H2(story, '4.3 Spring Task 定时任务与 cron')
make_table(story, ['任务', 'cron', '说明'], [
    ['<font name="CONSOLA" size="8.3">processPayment<br/>TimeoutOrder</font>', '0 * * * * ?（每分钟）', '状态=待付款 且 下单超 15 分钟 → 取消，原因「支付超时」'],
    ['<font name="CONSOLA" size="8.3">processDelivery<br/>TimeoutOrder</font>', '0 0 1 * * ?（每天凌晨 1 点）', '一直处于派送中的历史订单 → 置为已完成'],
], [0.24, 0.28, 0.48], cap='表 4-1 @Scheduled 定时任务')
callout(story, '面试高频：定时任务在集群下会有什么问题？',
 '多实例部署时每个节点都会触发一次，导致重复取消/重复扣减。解决：分布式锁（Redis setnx）、只让一个节点跑调度中心'
 '（XXL-JOB），或用 ShedLock。单机教学项目直接 @Scheduled 即可——主动指出这一点非常加分。')

H2(story, '4.4 微信支付与 POI 报表')
BL(story, [
 '<b>微信支付（JSAPI）</b>：后端调用统一下单接口拿到 prepayId，返回给小程序调起支付；支付结果由微信<b>异步回调</b> '
 '/notify/paySuccess 通知后端（需 cpolar 内网穿透让公网可达），验签通过后修改订单状态并推送来单提醒。'
 '回调幂等：先按订单号查状态，已支付则直接返回成功。',
 '<b>Apache POI 报表</b>：读取模板 Excel，按行写入近 30 天营业额/有效订单等数据，通过 HttpServletResponse 以附件流下载。'
 '日期区间统计用「按天循环 + Mapper 聚合」，销量 Top10 对 order_detail 按菜品名聚合求和取前 10。'])

# ═══ 第五章 AI Agent 功能 ═══
H1(story, '第五章 我加的亮点：AI 智能运营 Agent')

H2(story, '5.1 功能与效果')
P(story, '在<b>不改动原有分层架构</b>的前提下新增两个接口（挂 /admin/ai/**，复用既有 JWT 拦截与 Knife4j 文档）：')
make_table(story, ['接口', '功能', '示例'], [
    ['<font name="CONSOLA" size="8.3">POST /admin/ai/<br/>agent/chat</font>', '智能运营助手（多轮 + 工具调用）', '「今天生意怎么样？哪道菜卖得最好？」'],
    ['<font name="CONSOLA" size="8.3">POST /admin/ai/<br/>dish/copywriting</font>', '按菜品生成 30 字售卖文案', 'dishId=46 → 「王老吉：冰镇去腻…」'],
], [0.24, 0.32, 0.44], cap='表 5-1 新增 AI 接口')
P(story, 'Agent 收到问题后<b>自主决定</b>调用哪些店内工具（4 个：今日营业数据、销量 Top10、菜品检索、订单统计），'
 '工具全部<b>复用现有 Service/Mapper</b>，查询的是真实业务数据而不是模型编造的数字；响应中的 toolTrace 字段'
 '记录了完整调用轨迹，便于调试与展示。', body_ni)

H2(story, '5.2 Agent 工具调用循环（核心）')
fig(story, fig_agent(), '图 5-1 Tool-Calling Agent 循环（ReAct 思想）')
BL(story, [
 '<b>设计决策 1｜复用业务层</b>：工具就是 Java 方法，直接调用 WorkspaceService / OrderMapper 等。Agent 与业务同库同源，没有数据同步成本。',
 '<b>设计决策 2｜OpenAI 兼容协议</b>：AiClientUtil 对接 /chat/completions，base-url/model/api-key 可配，智谱 GLM、DeepSeek、通义可即插即换。',
 '<b>设计决策 3｜会话记忆放 Redis</b>：按 sessionId 用 List 存 JSON 消息，滑动窗口保留最近 20 条。TTL 2 小时自动过期，重启不丢。',
 '<b>设计决策 4｜工程化兜底</b>：未配 Key 返回友好提示而非报错；工具执行 try-catch 后把错误 JSON 回填给模型；MAX_ITERATIONS=6 防死循环。'])

H2(story, '5.3 面试怎么讲（30 秒电梯稿 + 追问预案）')
callout(story, '电梯稿',
 '「我在外卖项目里做了一个 Tool-Calling Agent：管理员用自然语言问经营问题，大模型通过 function calling '
 '自主选择调用我定义的四个业务工具，工具复用现有 Service 层查真实数据，结果回填后模型汇总成带建议的回答。'
 '多轮会话存 Redis，接口未配 Key 时优雅降级。它演示了把 LLM 嵌入真实工程的三件套：工具编排、上下文管理、兜底设计。」')
make_table(story, ['面试官可能追问', '回答要点'], [
    ['这和普通调一次大模型接口有什么区别？', '普通调用是单轮问答；Agent 是「模型决定工具、服务端执行、结果回填、循环到满意」的闭环，模型获得自主规划能力，能回答「先查销量、再对照营业数据给建议」这类复合问题。'],
    ['幻觉问题怎么控制？', '系统提示词强制「涉及数据必须先调工具」；工具结果以 role=tool 注入上下文，数字来自数据库而非模型记忆；toolTrace 可人工审计每一次取数。'],
    ['工具执行失败/超时怎么办？', 'try-catch 后把 {"error":...} 回填，模型会向用户解释或换工具；单轮最多 6 次迭代防死循环；HTTP 60s 超时熔断。'],
    ['上下文超长怎么办？', '滑动窗口只保留最近 20 条消息（可升级为摘要压缩）；Redis TTL 2 小时自动过期。'],
    ['为什么不用 LangChain？', '工具执行就在现有 Service 层，手写循环不到 200 行，依赖少、行为可控、便于排查；LangChain 的价值在复杂编排场景，此处引入反而重。'],
    ['怎么保证提示词注入安全？', '工具只暴露只读查询（无写操作），即使被诱导也只是泄露经营数据粒度；生产上还应限制可调工具白名单并审计日志。'],
], [0.3, 0.7], cap='表 5-2 Agent 高频追问与回答要点')

# ═══ 第六章 面试问答快查 ═══
H1(story, '第六章 面试问答快查（18 题）')

def qa_group(story, pairs):
    for q, a in pairs:
        story.append(KeepTogether([Paragraph('Q：' + q, qa_q), Paragraph('A：' + a, qa_a)]))

H2(story, '6.1 基础与架构（6 题）')
QAS = [
 ('项目难点是什么？', '按「技术点 + 解决的问题」答：①@AutoFill 用 AOP+反射消除 30+ 处重复 set 代码；②菜品缓存用 Spring Cache 注解化，并解决写操作后的一致性；③WebSocket 解决来单实时触达；④AI Agent 把 LLM 接入真实业务数据。'),
 ('JWT 相比 Session 的优劣？', '无状态、适合分布式，服务端不存会话；但签发后无法主动作废（只能短 TTL+刷新），敏感操作需二次校验。项目用 2 小时 TTL。'),
 ('拦截器和过滤器的区别？', '过滤器是 Servlet 规范、拿不到 Spring Bean 上下文语义；拦截器是 Spring MVC 机制，能注入 Bean、能感知 handler 方法。JWT 校验用拦截器 + WebMvcConfiguration 注册并排除登录路径。'),
 ('为什么 MD5 存密码？安全吗？', '教学项目沿用了 MD5；生产环境应当用 BCrypt 加盐 + 慢哈希。面试可主动指出：MD5 已可被彩虹表碰撞，这是我审视过的安全改进点。'),
 ('Knife4j 是干嘛的？', 'Swagger 增强 UI：@Api/@ApiOperation 生成分组文档，doc.html 在线调试，前后端并行开发的接口契约。'),
 ('Controller 里为什么几乎没业务代码？', 'Controller 只做参数接收、校验与 Result 包装；业务在 Service，数据在 Mapper。三层职责分离后单测和复用都更容易——我的 Agent 工具直接复用 Service 就是收益。'),
]
qa_group(story, QAS)
H2(story, '6.2 Redis 与性能（4 题）')
QAS2 = [
 ('什么数据适合缓存？', '读多写少且允许短暂不一致：菜品/套餐列表。订单、库存类强一致数据不缓存。'),
 ('Spring Cache 和手写 RedisTemplate 怎么选？', '注解（@Cacheable/@CacheEvict）零侵入、key 用 SpEL；但灵活性低。项目里读走注解、店铺状态开关这种简单 KV 走 RedisTemplate。'),
 ('缓存穿透/击穿/雪崩？', '穿透：查不存在的数据——缓存空对象或布隆过滤器；击穿：热点 key 过期瞬间——互斥锁/逻辑过期；雪崩：大批 key 同时过期——TTL 加随机。菜品缓存可按这些思路扩展。'),
 ('Redis 挂了会怎样？', '读接口降级查库（Spring Cache 本身允许穿透到方法），性能下降但可用；Agent 会话历史丢失只影响多轮上下文，重新开始对话即可。'),
]
qa_group(story, QAS2)
H2(story, '6.3 业务与工程（4 题）')
QAS3 = [
 ('下单有没有并发问题？', '演示版未做库存扣减。若扩展秒杀需要两件事：「判断+扣减」原子化（Redis 预扣 + Lua 或数据库乐观锁）防超卖；幂等设计——下单前先检查该用户是否存在未支付订单。'),
 ('逻辑外键的好处与代价？', '好处：写入无需约束检查、扩展灵活；代价：应用层要自己维护一致性（先查后改）。结合删除套餐前校验在售状态举例。'),
 ('批量插入怎么做的？', 'order_detail 用 XML foreach 拼多值 insert，一次网络往返，比循环单插快一个数量级。'),
 ('事务怎么保证？', '下单「插订单+插明细+清购物车」在同一 Service 方法，靠 @Transactional（默认 RuntimeException 回滚）保证原子性；注意捕获异常后必须再抛出，否则事务失效。'),
]
qa_group(story, QAS3)
H2(story, '6.4 AI Agent（4 题）')
QAS4 = [
 ('Agent 的工具是怎么注册的？', '服务端维护一份 OpenAI function calling 格式的 JSON Schema（名称+描述+参数），随每次请求发给模型；执行侧用 switch 路由到对应 Java 方法。描述写得越准，模型选择越稳。'),
 ('多轮上下文怎么管理？', 'Redis List 按 sessionId 存 JSON 消息，读时拼进 messages 数组，滑动窗口 20 条 + TTL 2h；这是「会话即数据」的最简实现，生产可换摘要压缩或专用记忆服务。'),
 ('成本与时延怎么考虑？', '每次工具轮次都是一次模型请求，复合问题会多次往返。可用 glm-4-flash 等免费模型起步；重要链路对「问题-回答」做缓存，或用本地小模型做意图路由。'),
 ('如果让 Agent 支持写操作（改价格/下架）？', '必须加人工确认环节（把「待执行动作」返回前端二次确认）+ 权限校验 + 操作审计；不能让模型直接触达写接口。'),
]
qa_group(story, QAS4)

# ═══ 第七章 话术与速查 ═══
H1(story, '第七章 开场话术与启动速查')

H2(story, '7.1 三分钟项目介绍（可直接背）')
callout(story, '开场 30 秒',
 '「苍穹外卖是一套前后端分离的餐饮 SaaS 点餐系统，管理端 Vue + 用户端小程序，后端 Spring Boot 单体三模块。'
 '我负责完整实现并二次增强：基础功能覆盖员工/菜品/套餐/订单/报表全链路，技术上以 JWT+ThreadLocal 登录链、'
 'AOP 公共字段填充、Spring Cache 菜品缓存、WebSocket 来单提醒和定时订单清理为核心。'
 '在此基础上我加了一个 Tool-Calling 智能运营 Agent，让管理员用自然语言查真实经营数据。」')
callout(story, '展开主线（挑 2-3 个讲深）',
 '①登录链路：MD5 校验 → JWT 签发 → 拦截器解析 → ThreadLocal 传递 → AOP 自动填充 create_user，一条线串起五个技术点；'
 '②缓存一致性：@Cacheable 读 + @CacheEvict 写删除，为什么删除而不是更新；'
 '③AI Agent：工具定义、循环执行、Redis 会话、优雅降级四件套。')

H2(story, '7.2 本地启动速查')
code_block(story, '''# 1. 初始化数据库（含 11 张表 + 种子数据）
mysql -uroot -p < sql/sky_take_out.sql

# 2. 改配置：sky-server/src/main/resources/application-dev.yml
#    MySQL 账号密码、Redis 密码、（可选）sky.ai.api-key

# 3. 打包并启动后端（JDK 17）
cd sky-take-out && mvn package -DskipTests
java -jar sky-server/target/sky-server-1.0-SNAPSHOT.jar

# 4. 启动管理端（nginx 反代 /api/ → 8080）
cd qianduan/nginx-1.20.2 && nginx.exe
# 访问 http://localhost  管理端账号 admin / 123456
# 接口文档 http://localhost:8080/doc.html''')

H2(story, '7.3 面试前自查清单')
BL(story, [
 '能白板画出图 1-1 的四层架构，并说出每一层放什么、不放什么。',
 '能不看资料讲完「登录链路」：MD5 校验 → JWT 签发 → 拦截器解析 → ThreadLocal → AOP 填充 create_user。',
 '能说出缓存为什么「删而不更」，以及写操作后缓存如何保持一致。',
 '能讲清 AI Agent 的一次完整循环：请求带工具定义 → tool_calls → 执行工具 → 结果回填 → 最终回答。',
 '能回答至少 5 个追问：事务失效场景、ThreadLocal 为什么要 remove、定时任务集群重复执行、JWT 无法主动作废、Agent 幻觉控制。',
 '本地项目能 10 分钟内跑起来（数据库导入 + 配置 + java -jar），现场演示 Agent 对话最有说服力。'])

doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('body.pdf 生成完成')
